### ISSUE TITLE
Add filter by evalue function

### ISSUE THREAD

**Issue by currocam** [currocam/HMMERutils#10]
Añadir una función que filtre los resultados en base al Evalue. Hay tres tipos de Evalue:
1. El Evalue de las secuencias -> hits.evalue
2. El Evalue del dominio de cada secuencia condicionado a que la secuencia sí sea significativa -> domains.cevalue
2. El Evalue del dominio de cada secuencia independiente a que la secuencia sea significativa -> domains.ievalue

Expected behaviour:
```r
library(HMMERutils)
nrow(phmmer_2abl)
filtered <- HMMERutils::filter_hmmer(phmmer_2abl, threshold = 0.0005, by = "hits.evalue")
nrow(filtered) == 14
filtered <- HMMERutils::filter_hmmer(phmmer_2abl, threshold = 0.0005, by = "domains.evalue")
nrow(filtered) == 22
filtered <- HMMERutils::filter_hmmer(phmmer_2abl, threshold = 0.0005, by = "domains.ievalue")
nrow(filtered) == 13
```

**Comment by Juane99** [comment]
He ejecutado la función usando el dataframe phmmer_2abl y no obtengo el mismo número de filas, es posible que se deba a que he vuelto a crear el dataset en local a partir del script 2abl_phmmer.R y haya cambiado la información.

Por otra parte, por confirmar que no he cometido un error, ¿el parámetro "by" de la segunda llamada de la imagen de arriba no debería ser "domains.cevalue"?

![image](https://user-images.githubusercontent.com/33232217/200653642-ada6cebb-e47f-41b5-b3e0-1a66551c682f.png)
