### ISSUE TITLE
[BUG] Fix Ubuntu Set BiocVersion

### ISSUE THREAD

**Issue by currocam** [currocam/HMMERutils#6]
Yo diría que el problema no es ni con el docker ni con el GiHub Action, sino con las dependencias. Biocversion no es capaz de encontrar versiones adecuadas para satisfacer las dependencias. Habría que verlo, probablemente usando un Ubuntu. 

https://www.bioconductor.org/packages/release/bioc/html/BiocVersion.html

**Comment by Juane99** [comment]
Vale, voy a echarle un vistazo. También voy a modificar la ruta de donde se descarga el dataframe necesario para los ejemplos, que al cambiar el nombre de la PR ya no lo encuentra.
